; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc1-n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 115200
monitor_raw = yes

build_unflags = -std=gnu++11
                '-D ARDUINO_USB_MODE'

lib_deps =
;    AdaFruit/Adafruit ST7735 and ST7789 Library@^1.11.0
    bodmer/TFT_eSPI
build_flags =
    -std=gnu++17
    -D BAUD_RATE=115200
    '-D ARDUINO_USB_CDC_ON_BOOT=1'
    -D USER_SETUP_LOADED=1         ; Tells the library to ignore its internal User_Setup.h
    -include include/TFT_Setup.h   ; Forces the compiler to inject your custom settings